name: data-science-demo
on:
  push:
    #paths:
    # - 'data_science_notebook.ipynb'
    paths-ignore:
      - 'README'
      - 'License'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        make install
    #- name: Lint
    #   run: |
    #     make lint
    - name: Test
      run: |
        make test
